---
title: "expected_counts"
author: "Nobuaki Masaki"
date: "5/1/2024"
output: html_document
---

```{r, include=FALSE}
library(dplyr)
library(tidyr)
library(ggplot2)
library(zoo)
source('../main_sim/fns_sim.R')

pL_geom_1M <- function(l, psi, phi, M) {
  if (l == 1) {return(phi*psi/(phi*psi + psi^2*(1 - phi - (1 - phi)^M)))}
  else {return(phi*(1-phi)^(l-1)*psi^2/(phi*psi + psi^2*(1 - phi - (1 - phi)^M)))}
}

get_exp_freq_1M <- function(psi, phi, M) {
  density <- lapply(1:1500, pL_geom_1M, psi, phi, M) %>% unlist()
  return(density)
}

get_exp_freq_2M <- function(psi, phi, M) {
  density <- lapply(2:1500, pL_geom_2M, psi, phi, M) %>% unlist()
  return(density)
}

sim.0.5 <- readRDS("../main_sim/res.sim.2M.1500.region.5000.ibdclust2cM.MAF.0.5.boot.keep.ends.rds")
sim.0.5.l <- lapply(sim.0.5, function(x) {return(x[[3]])}) %>% unlist()
sim.0.5.psi <- lapply(sim.0.5, function(x){return(x[[4]])}) %>% unlist() 

keep <- which(sim.0.5.l <= 1500)
sim.0.5.l <- sim.0.5.l[keep]
sim.0.5.psi <- sim.0.5.psi[keep]
```

```{r}
### General outline for LD section

#1. expected CDF not equal to empirical CDF in main simulation
  # - LD is changing the density at L = 1
#2  truncated expected CDF is equal to truncated empirical CDF in main simulation
  # - LD does not affect the rest of the distribution as much
#3. empirical CDF in main simulation is equal to empirical CDF when simulating from the vcf file
  # - observed tracts are detected correctly
#4. expected CDF is equal to empirical CDF when simulating tracts without LD
  # - proof of LD
```

```{r}
#1 and #2

# expected CDF in main simulation
sim.exp.freq.1M <- lapply(sim.0.5.psi, get_exp_freq_1M, 1/300, 1500)
sim.exp.freq.1M.matrix <- sim.exp.freq.1M %>% unlist() %>% matrix(ncol = 1500, byrow = TRUE)
sim.exp.freq.df <- colSums(sim.exp.freq.1M.matrix) %>% as.data.frame()
sim.exp.freq.df$l <- 1:1500
sim.exp.freq.df$freq <- sim.exp.freq.df$./sum(sim.exp.freq.df$.)

sim.obs.cnts <- as.data.frame(sim.0.5.l)
colnames(sim.obs.cnts) = "l"
sim.obs.cnts <- as.data.frame(sim.obs.cnts)
sim.obs.cnts.df <- sim.obs.cnts %>% group_by(l) %>% summarize(counts = n())
sim.obs.freq.df <- sim.obs.cnts.df
sim.obs.freq.df$freq <- sim.obs.freq.df$counts/sum(sim.obs.freq.df$counts)

sim.exp.freq.df$cdf.exp <- cumsum(sim.exp.freq.df$freq)
sim.obs.freq.df$cdf.emp <- cumsum(sim.obs.freq.df$freq)

exp.freq.2M.df <- get_exp_freq_2M(1, 1/300, 1500) %>% as.data.frame()
exp.freq.2M.df$l <- 2:1500
exp.freq.2M.df$cdf.exp.trunc <- cumsum(exp.freq.2M.df$.)

sim.obs.freq.df$freq.trunc <- sim.obs.freq.df$freq/(sum(sim.obs.freq.df$freq) - sim.obs.freq.df$freq[1])
sim.obs.freq.df$freq.trunc <- c(0, sim.obs.freq.df$freq.trunc[-1]) 
sim.obs.freq.df$cdf.emp.trunc <- cumsum(sim.obs.freq.df$freq.trunc)

sim.freq.df <- left_join(sim.exp.freq.df, sim.obs.freq.df, by = "l") %>% left_join(exp.freq.2M.df, by = "l") %>% select(l, cdf.exp, cdf.emp, cdf.exp.trunc, cdf.emp.trunc) %>% gather(2:5, key = "analysis", value = "cdf")

sim.freq.df$analysis <- forcats::fct_relevel(sim.freq.df$analysis, "cdf.exp", "cdf.emp", "cdf.exp.trunc", "cdf.emp.trunc")

sim.freq.df$cdf <- na.locf(sim.freq.df$cdf)

p1 <- ggplot(sim.freq.df %>% filter(analysis %in% c("cdf.exp", "cdf.emp")), aes(x = l, y = cdf, color = analysis)) + geom_line(size = 1, alpha = 0.5) + theme_bw() + labs(title = "A", y = "Cumulative density", x = expression(italic(l)), color = "") + theme(text = element_text(size=22), plot.title = element_text(hjust = 0)) + ylim(0, 1.01) + 
  scale_color_manual(
  values = c("cdf.exp" = "#000000", "cdf.emp" = "#E41A1C"), 
  labels = c(expression(F[1]^1500~(l)), expression(paste(widehat(F)^{multiIBD}, (l))))) +
  scale_x_continuous(breaks = c(1, 500, 1000, 1500))

p1

ggsave("cdf.p1.png", width = 12, height = 6)

p2 <- ggplot(sim.freq.df %>% filter(analysis %in% c("cdf.exp.trunc", "cdf.emp.trunc") & l > 1), aes(x = l, y = cdf, color = analysis)) + geom_line(size = 1, alpha = 0.5) + theme_bw() + labs(title = "B", y = "Cumulative density", x = expression(italic(l)), color = "") + theme(text = element_text(size=22), plot.title = element_text(hjust = 0)) + ylim(-0.01, 1.01) + xlim(2, 1500) + 
  scale_color_manual(
  values = c("cdf.exp.trunc" = "#000000", "cdf.emp.trunc" = "#E41A1C"), 
  labels = c(expression(F[2]^1500~(l)), expression(paste(widehat(F)^{multiIBD}, (l))))) +
  scale_x_continuous(breaks = c(2, 500, 1000, 1500))

p2

ggsave("cdf.p2.png", width = 12, height = 6)
```

```{r}
#3

sim.vcf <- read.csv("../sim_vcf/sim_tracts_vcf_5000000.csv")
sim.vcf <- sim.vcf %>% filter(X0 <= 1500)
sim.vcf.df <- sim.vcf %>% group_by(X0) %>% summarize(count = n())
sim.vcf.df <- sim.vcf.df[-1,]
sim.vcf.df$freq <- sim.vcf.df$count/sum(sim.vcf.df$count)
sim.vcf.df$cdf <- cumsum(sim.vcf.df$freq)
sim.vcf.df$l <- sim.vcf.df$X0
sim.vcf.df$analysis <- "cdf.emp.vcf"
sim.vcf.df <- select(sim.vcf.df, l, analysis, cdf)

sim.freq.df <- rbind(sim.freq.df, sim.vcf.df)

sim.freq.df$analysis <- forcats::fct_relevel(sim.freq.df$analysis, "cdf.exp", "cdf.emp", "cdf.exp.trunc", "cdf.emp.trunc", "cdf.emp.vcf")

sim.freq.df$cdf <- na.locf(sim.freq.df$cdf)

p3 <- ggplot(sim.freq.df %>% filter(analysis %in% c("cdf.emp", "cdf.emp.vcf")), aes(x = l, y = cdf, color = analysis)) + geom_line(size = 1, alpha = 0.5) + theme_bw() + labs(y = "Cumulative density", x = expression(italic(l)), color = "") + theme(text = element_text(size=22), plot.title = element_text(hjust = 0.5)) + ylim(0, 1.01) + 
  scale_color_manual(
  values = c("cdf.emp" = "#E41A1C", "cdf.emp.vcf" = "#377EB8"), 
  labels = c(expression(paste(widehat(F)^{multiIBD}, (l))), expression(paste(widehat(F)^{individuals}, (l))))) +
  scale_x_continuous(breaks = c(1, 500, 1000, 1500))

p3

ggsave("cdf.p3.png", width = 9, height = 6)
```

```{r}
#4

sim.tracts <- readRDS("../sim_tracts/res.geom.rds")
sim.tracts.l <- sim.tracts[[1]][[4]]
sim.tracts.psi <- sim.tracts[[1]][[5]]

keep <- which(sim.tracts.l <= 1500)
sim.tracts.l <- sim.tracts.l[keep]
sim.tracts.psi <- sim.tracts.psi[keep]

# expected CDF
sim.exp.freq.1M <- lapply(sim.tracts.psi, get_exp_freq_1M, 1/300, 1500)
sim.exp.freq.1M.matrix <- sim.exp.freq.1M %>% unlist() %>% matrix(ncol = 1500, byrow = TRUE)
sim.exp.freq.df <- colSums(sim.exp.freq.1M.matrix) %>% as.data.frame()
sim.exp.freq.df$l <- 1:1500
sim.exp.freq.df$freq <- sim.exp.freq.df$./sum(sim.exp.freq.df$.)

sim.obs.cnts <- as.data.frame(sim.tracts.l)
colnames(sim.obs.cnts) = "l"
sim.obs.cnts <- as.data.frame(sim.obs.cnts)
sim.obs.cnts.df <- sim.obs.cnts %>% group_by(l) %>% summarize(counts = n())
sim.obs.freq.df <- sim.obs.cnts.df
sim.obs.freq.df$freq <- sim.obs.freq.df$counts/sum(sim.obs.freq.df$counts)

sim.exp.freq.df$cdf.exp <- cumsum(sim.exp.freq.df$freq)
sim.obs.freq.df$cdf.emp <- cumsum(sim.obs.freq.df$freq)

sim.freq.df <- left_join(sim.exp.freq.df, sim.obs.freq.df, by = "l") %>% select(l, cdf.exp, cdf.emp) %>% gather(2:3, key = "analysis", value = "cdf")

sim.freq.df$analysis <- forcats::fct_relevel(sim.freq.df$analysis, "cdf.exp", "cdf.emp")

sim.freq.df$cdf <- na.locf(sim.freq.df$cdf)

p4 <- ggplot(sim.freq.df %>% filter(analysis %in% c("cdf.exp", "cdf.emp")), aes(x = l, y = cdf, color = analysis)) + geom_line(size = 1, alpha = 0.5) + theme_bw() + labs(y = "Cumulative density", x = expression(italic(l)), color = "") + theme(text = element_text(size=22), plot.title = element_text(hjust = 0.5)) + ylim(0, 1.01) + 
  scale_color_manual(
  values = c("cdf.exp" = "#000000", "cdf.emp" = "#E41A1C"), 
  labels = c(expression(F[1]^1500~(l)), expression(paste(widehat(F)^{noLD}, (l))))) +
  scale_x_continuous(breaks = c(1, 500, 1000, 1500))

p4

ggsave("cdf.p4.png", width = 9, height = 6)
```









