---
title: "test"
output: html_document
date: "2024-08-24"
---

```{r}
library(dplyr)
source("../main_sim/fns_sim.R")

pL_geom_2M <- function(l, phi, M) {
  denom <- (1-phi)-(1-phi)^M
  num <- phi*(1-phi)^(l-1)
  return(num/denom)
}

pL_geom2_2M <- function(l, psi, phi, M) {
  C <- phi + psi - phi*psi
  denom <- C*( (3-M)*phi*(1-phi)^(M-1) - (1-phi)^(M-1) - 2*phi + 1 ) + 2*phi*(1-(1-phi)^(M-1))
  num <- C*(l-3)*phi^2*(1-phi)^(l-2) + 2*phi^2*(1-phi)^(l-2)
  return(num/denom)
}

lapply(2:20, pL_geom2_2M, 0.1, 0.3, 1000) %>% unlist()
lapply(2:20, pL_geom2_1M, 0.1, 0.3, 1000) %>% unlist()

lapply(2:1000, pL_geom2_2M, 0.1, 0.3, 1000) %>% unlist() %>% sum()
```

```{r}
pL_geom_1M(100, 0.2, 0.1, 1000)
pL_geom_2M(100, 0.1, 1000)
lapply(2:1000, pL_geom_2M, 0.1, 1000) %>% unlist() %>% sum()
```

```{r}
## testing distributions for N in sim

# Load necessary package
library(ggplot2)

x_values <- 1:2000

# Calculate PMF values
pmf_geom <- dgeom(x_values, prob = 1/300)
pmf_geom2 <- dgeom(x_values, prob = 1/150) + dgeom(x_values, prob = 1/150)
pmf_neg_binom <- dnbinom(x_values, size = 3, mu = 300)

# Create a data frame for plotting
data <- data.frame(
  x = x_values,
  Geometric = pmf_geom,
  Geometric_sum = pmf_geom2,
  Neg_binom = pmf_neg_binom
)

# Convert data to long format for ggplot2
data_long <- tidyr::pivot_longer(data, cols = c("Geometric", "Geometric_sum", "Neg_binom"), names_to = "Distribution", values_to = "PMF")

# Plot the PMFs using ggplot2
ggplot(data_long, aes(x = x, y = PMF, color = Distribution)) +
  geom_point() +
  geom_line() +
  labs(x = "x",
       y = "Probability Mass Function (PMF)") +
  theme_minimal()
```

```{r}
mean(rgeom(1000000, 1/150) + rgeom(1000000, 1/150) + 2)

mean(rnbinom(n = 100000000, size = 3, mu = 300))
```

