---
title: "analysis"
output: html_document
date: "2024-10-13"
---

```{r setup, include=FALSE}
library(dplyr)
geom.res <- readRDS("res.sim.2M.1500.region.5000.geom.MAF.0.5.boot.keep.ends.rds")
geom2.res <- readRDS("res.sim.2M.1500.region.5000.geom2.MAF.0.5.boot.keep.ends.rds") 
geom3.res <- readRDS("res.sim.2M.1500.region.5000.geom3.MAF.0.5.boot.keep.ends.rds") 

unif.1.res <- readRDS("res.sim.2M.1500.region.5000.unif.MAF.0.5.boot.keep.ends.1.rds") 
unif.2.res <- readRDS("res.sim.2M.1500.region.5000.unif.MAF.0.5.boot.keep.ends.1.rds") 
unif.res <- c(unif.1.res, unif.2.res)
```

```{r}
geom.pnt.geom <- lapply(geom.res, function(x) {x[[1]][[1]]}) %>% unlist()
geom2.pnt.geom <- lapply(geom2.res, function(x) {x[[1]][[1]]}) %>% unlist()
geom3.pnt.geom <- lapply(geom3.res, function(x) {x[[1]][[1]]}) %>% unlist()
unif.pnt.geom <- lapply(unif.res, function(x) {x[[1]][[1]]}) %>% unlist()

geom.pnt.geom2 <- lapply(geom.res, function(x) {x[[2]][[1]]}) %>% unlist()
geom2.pnt.geom2 <- lapply(geom2.res, function(x) {x[[2]][[1]]}) %>% unlist()
geom3.pnt.geom2 <- lapply(geom3.res, function(x) {x[[2]][[1]]}) %>% unlist()
unif.pnt.geom2 <- lapply(unif.res, function(x) {x[[2]][[1]]}) %>% unlist()
```

```{r}
### geometric model
mean(1/geom.pnt.geom) - 300
mean(1/geom2.pnt.geom) - 300
mean(1/geom3.pnt.geom) - 300
mean(1/unif.pnt.geom) - 300

### geometric 2 model
mean(2/geom.pnt.geom2) - 300
mean(2/geom2.pnt.geom2) - 300
mean(2/geom3.pnt.geom2) - 300
mean(2/unif.pnt.geom2) - 300

### geometric model
sd(1/geom.pnt.geom) 
sd(1/geom2.pnt.geom) 
sd(1/geom3.pnt.geom) 
sd(1/unif.pnt.geom) 

### geometric 2 model
sd(2/geom.pnt.geom2) 
sd(2/geom2.pnt.geom2) 
sd(2/geom3.pnt.geom2) 
sd(2/unif.pnt.geom2) 
```

```{r}
geom.lik.geom <- lapply(geom.res, function(x) {x[[1]][[2]]}) %>% unlist()
geom2.lik.geom <- lapply(geom2.res, function(x) {x[[1]][[2]]}) %>% unlist()
geom3.lik.geom <- lapply(geom3.res, function(x) {x[[1]][[2]]}) %>% unlist()
unif.lik.geom <- lapply(unif.res, function(x) {x[[1]][[2]]}) %>% unlist()

geom.lik.geom2 <- lapply(geom.res, function(x) {x[[2]][[2]]}) %>% unlist()
geom2.lik.geom2 <- lapply(geom2.res, function(x) {x[[2]][[2]]}) %>% unlist()
geom3.lik.geom2 <- lapply(geom3.res, function(x) {x[[2]][[2]]}) %>% unlist()
unif.lik.geom2 <- lapply(unif.res, function(x) {x[[2]][[2]]}) %>% unlist()

geom.pnt.AIC <- ifelse(geom.lik.geom < geom.lik.geom2, 1/geom.pnt.geom, 2/geom.pnt.geom2)
geom2.pnt.AIC <- ifelse(geom2.lik.geom < geom2.lik.geom2, 1/geom2.pnt.geom, 2/geom2.pnt.geom2)
geom3.pnt.AIC <- ifelse(geom3.lik.geom < geom3.lik.geom2, 1/geom3.pnt.geom, 2/geom3.pnt.geom2)
unif.pnt.AIC <- ifelse(unif.lik.geom < unif.lik.geom2, 1/unif.pnt.geom, 2/unif.pnt.geom2)
```

```{r}
mean(geom.pnt.AIC) - 300
mean(geom2.pnt.AIC) - 300
mean(geom3.pnt.AIC) - 300
mean(unif.pnt.AIC) - 300

sd(geom.pnt.AIC) 
sd(geom2.pnt.AIC)
sd(geom3.pnt.AIC) 
sd(unif.pnt.AIC) 
```

```{r}
geom.boot <- lapply(geom.res, function(x) {x[[5]] %>% unlist() %>% matrix(byrow = TRUE, ncol = 2) %>% apply(2, function(x) quantile(x, probs = c(0.025, 0.975)))}) 
geom2.boot <- lapply(geom2.res, function(x) {x[[5]] %>% unlist() %>% matrix(byrow = TRUE, ncol = 2) %>% apply(2, function(x) quantile(x, probs = c(0.025, 0.975)))}) 
geom3.boot <- lapply(geom3.res, function(x) {x[[5]] %>% unlist() %>% matrix(byrow = TRUE, ncol = 2) %>% apply(2, function(x) quantile(x, probs = c(0.025, 0.975)))}) 
unif.boot <- lapply(unif.res, function(x) {x[[5]] %>% unlist() %>% matrix(byrow = TRUE, ncol = 2) %>% apply(2, function(x) quantile(x, probs = c(0.025, 0.975)))}) 
```

```{r}
geom.coverage <- lapply(geom.boot, function(x) {c(x[1,1] <= 300 & 300 <= x[2,1], x[1,2] <= 300 & 300 <= x[2,2])}) %>% unlist() %>% matrix(byrow = TRUE, ncol = 2)
geom2.coverage <- lapply(geom2.boot, function(x) {c(x[1,1] <= 300 & 300 <= x[2,1], x[1,2] <= 300 & 300 <= x[2,2])}) %>% unlist() %>% matrix(byrow = TRUE, ncol = 2)
geom3.coverage <- lapply(geom3.boot, function(x) {c(x[1,1] <= 300 & 300 <= x[2,1], x[1,2] <= 300 & 300 <= x[2,2])}) %>% unlist() %>% matrix(byrow = TRUE, ncol = 2)
unif.coverage <- lapply(unif.boot, function(x) {c(x[1,1] <= 300 & 300 <= x[2,1], x[1,2] <= 300 & 300 <= x[2,2])}) %>% unlist() %>% matrix(byrow = TRUE, ncol = 2)
```

```{r}
apply(geom.coverage, 2, mean)
apply(geom.coverage, 2, sum)

apply(geom2.coverage, 2, mean)
apply(geom2.coverage, 2, sum)

apply(geom3.coverage, 2, mean)
apply(geom3.coverage, 2, sum)

apply(unif.coverage, 2, mean)
apply(unif.coverage, 2, sum)
```

```{r}
# Load the necessary libraries
library(ggplot2)
library(dplyr)

calc_pmf_geom <- function(n, phi) {(1-phi)^(n-1)*phi}
calc_pmf_geom2 <- function(n, phi) {(n-1)*(1-phi)^(n-2)*phi^2}
calc_pmf_geom3 <- function(n, phi) {choose(n-1, 2)*(1-phi)^(n-3)*phi^3}

# Define the range of x values (number of failures)
x <- 0:1500  # Adjust this range if needed

# Calculate the PMF for negative binomial and geometric distributions
pmf_geom <- lapply(x, calc_pmf_geom, phi = 1/300) %>% unlist()
pmf_geom2 <- lapply(x, calc_pmf_geom2, phi = 1/150) %>% unlist()
pmf_geom3 <- lapply(x, calc_pmf_geom3, phi = 1/100) %>% unlist()
pmf_uniform <- ifelse(x >= 1 & x <= 599, 1 / 599, 0)

pmf_geom[1] <- 0
pmf_geom2[1] <- 0
pmf_geom2[2] <- 0
pmf_geom3[1] <- 0
pmf_geom3[2] <- 0
pmf_geom3[3] <- 0

# Create a data frame for plotting all distributions
data <- data.frame(x = x, 
                   pmf_geom = pmf_geom,
                   pmf_geom2 = pmf_geom2,
                   pmf_geom3 = pmf_geom3,
                   pmf_uniform = pmf_uniform)

# Define a color blind-friendly palette
color_palette <- c("Geometric" = "#56B4E9",
                   "Sum of two geometric" = "#F0E442",
                   "Sum of three geometric" = "#E69F00", 
                   "Uniform" = "#009E73")

# Plot the PMF using ggplot2
ggplot(data) +
  geom_line(aes(x = x, y = pmf_geom, color = "Geometric"), size = 1) +
  geom_line(aes(x = x, y = pmf_geom2, color = "Sum of two geometric"), size = 1) +
  geom_line(aes(x = x, y = pmf_geom3, color = "Sum of three geometric"), size = 1) +
  geom_line(aes(x = x, y = pmf_uniform, color = "Uniform"), size = 1) +
  labs(title = "Density of four distributions",
       x = "n", y = "P(N=n)") +
  scale_color_manual(values = color_palette, breaks = c("Geometric", "Sum of two geometric", "Sum of three geometric", "Uniform")) +
  scale_x_continuous(limits = c(1, 1500), breaks = c(1, seq(250, 1500, by = 250))) +  # Start at 1 and set breaks
  theme_minimal() +
  theme(legend.title = element_blank())

ggsave("figs/pmf.png", width = 7, height = 5)
```

```{r}
### testing code
geom.tracts <- read.csv("sim_tracts_vcf_geom_multiple_iterations.csv")
geom.tracts.start <- geom.tracts[,1]
geom.tracts.end <- geom.tracts[,2]

read.MAF <- function(seed) {
  str = paste0("sim5_seed", seed,
               "_10Mb_n125000.gtstats")
  df <- read.table(str)
  return(df)
}

MAF.chr1 <- read.MAF(1)

sum(geom.tracts.start %in% MAF.chr1$V2)
```

