---
title: "detection"
output: html_document
date: "2024-10-30"
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)

recomb_rates <- readRDS("res_recombination_rates.rds")

get_hotspots <- function(chr) {
  recomb_rates.chr <- recomb_rates[[chr]][[1]]
  background.rate <- recomb_rates[[chr]][[2]]
  
  recomb_rates.chr$hotspot <- recomb_rates.chr$V1 > 5*background.rate

  # Add a grouping column to identify consecutive TRUE/FALSE sequences
  recomb_rates.chr <- recomb_rates.chr %>%
    mutate(group_id = cumsum(hotspot != lag(hotspot, default = first(hotspot))))
  
  recomb.hotspots.chr <- recomb_rates.chr %>%
  group_by(group_id) %>%
    summarize(
    first_marker = min(V2),
    last_marker = max(V3),
    first_pos = min(V4),
    last_pos = max(V5),
    hotspot = first(hotspot)) %>%
    select(-group_id) 
  
  recomb.hotspots.chr$length <- recomb.hotspots.chr$last_pos - recomb.hotspots.chr$first_pos + 1
  recomb.hotspots.chr$chr <- chr
  
  return(recomb.hotspots.chr)
}

hotspots.chrs <- lapply(1:22, get_hotspots)
saveRDS(hotspots.chrs, "hotspots.RDS")

hotspots.chrs.combined <- do.call(rbind, hotspots.chrs)
```

```{r}
### testing code
# chr <- 2
# 
# recomb_rates.chr <- recomb_rates[[chr]][[1]]
# background.rate <- recomb_rates[[chr]][[2]]
#   
# recomb_rates.chr$hotspot <- recomb_rates.chr$V1 > 5*background.rate
# 
# # Add a grouping column to identify consecutive TRUE/FALSE sequences
# recomb_rates.chr <- recomb_rates.chr %>%
# mutate(group_id = cumsum(hotspot != lag(hotspot, default = first(hotspot))))

# hotspots.chrs[[1]]
```

```{r}
hotspots.chrs.combined.only.hotspots <- hotspots.chrs.combined %>% filter(hotspot == TRUE)
hotspots.chrs.combined.only.hotspots %>% filter(length == max(length))

hotspots.chr21 <- hotspots.chrs.combined %>% filter(chr == 21)
hotspots.chr21

recomb.rates.chr21 <- recomb_rates[[21]][[1]]
background.chr21 <- recomb_rates[[21]][[2]]
recomb.rates.chr21$hotspot <- recomb.rates.chr21$V1 > 5*background.chr21

ggplot(hotspots.chr21 %>% filter(hotspot == TRUE)) +
  geom_rect(aes(xmin = first_pos/10^6, xmax = last_pos/10^6, ymin = log(5*background.chr21)-0.5, ymax = log(5*background.chr21)+0.5), fill = "#E41A1C", color = "#E41A1C", size = 0.1) +
  geom_point(data = recomb.rates.chr21, aes(x = center/10^6, y = log(V1)), size = 0.3, alpha = 0.4) +
  labs(x = "Position (Mb)", y = "Logged recombination rate (cM/Mb)", title = "Recombination hotspots on chromosome 21") +
  geom_hline(yintercept = log(5*background.chr21)) +
  theme_bw()

ggsave("../figs/Fig2.png", width = 7, height = 4)
```

```{r}
res.hotspot <- readRDS("../res.UK_Biobank.1M.1500.region.5000.ibdclust2cM.MAF.0.5.boot.grouped.keep.ends.hotspot.rds")
res.not.hotspot <- readRDS("../res.UK_Biobank.1M.1500.region.5000.ibdclust2cM.MAF.0.5.boot.grouped.keep.ends.not.hotspot.rds")
res <- readRDS("../res.UK_Biobank.1M.1500.region.5000.ibdclust2cM.MAF.0.5.boot.grouped.keep.ends.rds")

1/res[[1]][[1]]
2/res[[2]][[1]]

AIC.geom <- 2 + 2*res[[1]][[2]]
AIC.geom2 <- 2 + 2*res[[2]][[2]]
AIC.geom - AIC.geom2

lapply(res[[5]], function(x) {x[[1]]}) %>% unlist() %>% quantile(probs = c(0.025, 0.975))
lapply(res[[5]], function(x) {x[[2]]}) %>% unlist() %>% quantile(probs = c(0.025, 0.975))
```

```{r}
1/res.hotspot[[1]][[1]]
2/res.hotspot[[2]][[1]]

1/res.not.hotspot[[1]][[1]]
2/res.not.hotspot[[2]][[1]]

quantile(lapply(res.hotspot[[5]], function(x) {x[[1]]}) %>% unlist(), probs = c(0.025, 0.975))
quantile(lapply(res.hotspot[[5]], function(x) {x[[2]]}) %>% unlist(), probs = c(0.025, 0.975))

quantile(lapply(res.not.hotspot[[5]], function(x) {x[[1]]}) %>% unlist(), probs = c(0.025, 0.975))
quantile(lapply(res.not.hotspot[[5]], function(x) {x[[2]]}) %>% unlist(), probs = c(0.025, 0.975))

2 + 2*res.hotspot[[1]][[2]]
2 + 2*res.hotspot[[2]][[2]]

2 + 2*res.not.hotspot[[1]][[2]]
2 + 2*res.not.hotspot[[2]][[2]]
```
```{r}
# length(res.hotspot[[3]]) + length(res.not.hotspot[[3]])
# length(res[[3]])
# 
# res[[4]]
```

