---
title: "expected_counts"
author: "Nobuaki Masaki"
date: "5/1/2024"
output: html_document
---

```{r, include=FALSE}
library(dplyr)
library(pbapply)
library(ggplot2)
library(gridExtra)
library(cowplot)
source('fns_sim.R')

### In this file, we want to get the expected counts under the true model, and see if we are seeing excess or not enough singletons
sim.0.5 <- readRDS("res.sim.M.1500.region.5000.geom.ibdclust2cM.MAF.0.5.boot.keep.ends.rds")
tracts <- lapply(sim.0.5, function(x) {return(x[[2]])}) %>% unlist() %>% matrix(byrow = TRUE, ncol = 2)
psi <- lapply(sim.0.5, function(x){return(x[[3]])}) %>% unlist() 
```

```{r}
# ### get expected distribution for each psi
# get_exp_cnts <- function(psi, phi, M) {
#   density <- lapply(1:1500, pL_geom_M, psi, phi, M)
#   return(density)
# }
# res <- pblapply(psi, get_exp_cnts, phi = 1/300, M = 1500)
# saveRDS(res, "exp.cnts.tracts.rds")
# 
# ### aggregate the expected distribution to get expected counts
# exp.cnts <- res[[1]] %>% unlist()
# for (i in 2:length(res)) {
#   new_row <- res[[i]] %>% unlist()
#   exp.cnts <- colSums(rbind(exp.cnts, new_row))
# }
# saveRDS(exp.cnts, "exp.cnts.rds")
# 
### get observed counts
# obs.cnts <- split(tracts, seq(nrow(tracts))) %>% lapply(function(x) {x[[2]] - x[[1]] + 1}) %>% as.data.frame() %>% t()
# colnames(obs.cnts) = "l"
# obs.cnts <- as.data.frame(obs.cnts)
# saveRDS(obs.cnts, "obs.cnts.rds")
```

```{r}
exp.cnts <- readRDS("exp.cnts.rds")
exp.cnts.df <- cbind(1:1500, exp.cnts %>% as.data.frame())
obs.cnts <- readRDS("obs.cnts.rds")
obs.cnts.df <- obs.cnts %>% group_by(l) %>% summarize(counts = n())

colnames(obs.cnts.df) <- c("l", "counts")
colnames(exp.cnts.df) <- c("l", "counts")

### density at each observed tract length l
obs.cnts.df$freq <- obs.cnts.df$counts/sum(obs.cnts.df$counts)
exp.cnts.df$freq <- exp.cnts.df$counts/sum(exp.cnts.df$counts)

### density after truncating at 1
obs.cnts.df$freq.trunc <- obs.cnts.df$freq/(1-obs.cnts.df$freq[1])
obs.cnts.df$freq.trunc[1] <- 0
exp.cnts.df$freq.trunc <- exp.cnts.df$freq/(1-exp.cnts.df$freq[1])
exp.cnts.df$freq.trunc[1] <- 0
# exp.cnts.df.trunc <- exp.cnts.df[-1,]
# obs.cnts.trunc <- obs.cnts %>% filter(l != 1)

LD.cnts <- read.csv("L_5000000.061324.csv", header = FALSE) %>% filter(V1 >= 1 & V1 <= 1500)
# LD.trunc.cnts <- LD.cnts %>% filter(V1 >= 2 & V1 <= 1500)
LD.cnts.df <- LD.cnts %>% group_by(V1) %>% summarize(counts = n())
colnames(LD.cnts.df) <- c("l", "counts")
LD.cnts.df$freq <- LD.cnts.df$counts/sum(LD.cnts.df$counts)
LD.cnts.df$freq.trunc <- LD.cnts.df$freq/(1-LD.cnts.df$freq[1])
LD.cnts.df$freq.trunc[1] <- 0
```

```{r}
# model_quantiles <- function(p) {
#   q <- numeric(length(p))
#   for (i in seq_along(p)) {
#     q[i] <- exp.cnts.df$l[which(cumsum(exp.cnts.df$freq) >= p[i])[1]]
#   }
#   return(q)
# }
# 
# model_quantiles_trunc <- function(p) {
#   q <- numeric(length(p))
#   for (i in seq_along(p)) {
#     q[i] <- exp.cnts.df.trunc$l[which(cumsum(exp.cnts.df.trunc$freq.trunc) >= p[i])[1]]
#   }
#   return(q)
# }
# 
# p <- seq(0.001, 0.999, length.out = 10000)
# model_quantiles <- model_quantiles(p)
# model_quantiles_trunc <- model_quantiles_trunc(p)
```

```{r}
# qqplot(model_quantiles_trunc, obs.cnts.trunc$l,
#        main = "Q-Q plot against custom discrete distribution",
#        xlab = "Theoretical Quantiles",
#        ylab = "Sample Quantiles")
# abline(0, 1, col = "red")
```

```{r}
# qqplot(model_quantiles_trunc, LD.trunc.cnts$V1,
#        main = "Q-Q plot against custom discrete distribution",
#        xlab = "Theoretical Quantiles",
#        ylab = "Sample Quantiles")
# abline(0, 1, col = "red")
```

```{r}
### exp != emp sim
### exp trunc == emp sim trunc
exp.cnts.df$cdf <- cumsum(exp.cnts.df$freq)
obs.cnts.df$cdf <- cumsum(obs.cnts.df$freq)

exp.cnts.df$cdf.trunc <- cumsum(exp.cnts.df$freq.trunc)
obs.cnts.df$cdf.trunc <- cumsum(obs.cnts.df$freq.trunc)

p1 <- ggplot(obs.cnts.df, aes(x = l, y = cdf)) + geom_line(size = 1, alpha = 0.5) + geom_line(data = exp.cnts.df, color = "#E41A1C", size = 1, alpha = 0.5) + theme_bw() + labs(y = "CDF") + theme(text = element_text(size=15)) + ylim(0, 1)

p2 <- ggplot(obs.cnts.df %>% filter(l > 1), aes(x = l, y = cdf.trunc)) + geom_line(size = 1, alpha = 0.5) + geom_line(data = exp.cnts.df %>% filter(l > 1), color = "#E41A1C", size = 1, alpha = 0.5) + theme_bw() + labs(y = "") + 
  theme(text = element_text(size=15))       # Optional: Remove y-axis title)
```

```{r}
p1
```


```{r}
### emp vcf == emp sim
LD.cnts.df$cdf <- cumsum(LD.cnts.df$freq)

p3 <- ggplot(obs.cnts.df, aes(x = l, y = cdf)) + geom_line(size = 1, alpha = 0.5) + geom_line(data = LD.cnts.df, color = "#377EB8", size = 1, alpha = 0.5) + theme_bw() + labs(y = "CDF") + theme(text = element_text(size=15)) + 
  scale_color_brewer(palette = "Set1") + ylim(0, 1)
```

```{r}
p3
```

```{r}
# Create a custom legend
legend_labels <- c("Empirical CDF from simulation study", "Expected CDF from model (F(l))", "Empirical CDF from vcf file")
legend_colors <- c("#000000", "#E41A1C", "#377EB8")

# Create a data frame for the legend
legend_data <- data.frame(
  x = rep(1, length(legend_labels)),
  y = seq_along(legend_labels),
  label = legend_labels,
  color = legend_colors
)

legend_data$label <- factor(legend_data$label, levels = c("Empirical CDF from simulation study", "Expected CDF from model (F(l))", "Empirical CDF from vcf file"))
legend_data$color <- factor(legend_data$color, levels = c("#000000", "#E41A1C", "#377EB8"))

# Create a blank plot for the custom legend
legend_plot <- ggplot(legend_data, aes(x = x, y = y)) +
  geom_point(aes(color = color), size = 5) + theme_bw() +
  scale_color_manual(labels = c("Empirical CDF from simulation study", "Expected CDF from model (F(l))", "Empirical CDF from vcf file"), values = c("#000000", "#E41A1C", "#377EB8")) + 
  theme(legend.title = element_blank(), 
        legend.background = element_rect(color = "black", size = 0.5),  # Add a box around the legend
        legend.key = element_rect(fill = "white", color = "black"))     # Add a border to legend keys)
  
legend <- get_legend(legend_plot)
```

```{r}
legend
```


```{r}
grid <- arrangeGrob(p1, p2, p3, legend, ncol=2)
ggsave("LD.plot.png", grid, width=10, height=8)
```




